name: template_utils
description: A sample command-line application.
version: 1.0.0
# homepage: https://www.example.com

environment:
  sdk: ">=3.7.0 <4.0.0"

dependencies:
  mason: any
  collection: 1.19.1
  path: 1.9.1
  async: 2.13.0
  recase: 4.1.0

override_dependencies:
  archive: 4.0.7

dev_dependencies:
  lints: 2.0.0
  test: 1.25.15

